### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [kawamura-chuko/shinobue_fumen#35]
@kawamura-chuko 
リリースお疲れ様でした、下記の観点でレビューいたします！

```
1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

## READMEから課題解決する実装がされているか&動いている
自動作曲されてさらに音で聞ける機能があるのがいいですね、毎回決められたルールに従いランダムで曲を作成しているのでサービスとしてMVPとしてリリースできています！

## 静的コードチェックが入っている
rubocopを導入してしっかりコードの静的チェックされていますね。

## 就活において十分な技術力を示せる機能を実装しているか
自動で曲を作成するロジックは篠笛、音楽の知識とプログラミングのアルゴリズム知識が生かされていますね。
Railsの機能的には物足りない部分はあるので、本リリースまでにフィードバックをもらいながら追加機能の実装や下記の内容を参考に技術アピールになる機能を実装しておきましょう。
私のおすすめは自動で作成した曲のデータと似ている登録曲のレコメンド機能などが面白そうです！

#### 概要
FacebookメッセンジャーやSNSなどには、チャット機能が必ずついています。現在では、WebSocketを用いることで、リアルタイムでやり取りが可能となっています。コツさえ掴めば、比較的簡単に実装できます。ダイレクトメッセージのようなチャット機能を実装することで、ユーザー同士のコミュニケーションを活性化させることができるかもしれません。
#### 使用技術・ライブラリ
* WebSocket
    * https://ja.wikipedia.org/wiki/WebSocket
* ActionCable（Rails標準）
    * https://railsguides.jp/action_cable_overview.html

#### 概要
投稿されたまたは事前に用意されたコンテンツと類似したコンテンツを推奨する機能をレコメンドと呼びます。代表的なアルゴリズムとして、協調フィルタリングとコンテンツフィルタリングがあります。協調フィルタリングは、ユーザの行動や嗜好データを元に類似度を算出し、コンテンツベースフィルタリングは、コンテンツの数値化された特徴や評価を元に類似度を算出します。

#### 使用技術・ライブラリ
* Amazon Personalize
    * https://docs.aws.amazon.com/ja_jp/personalize/latest/dg/what-is-personalize.html
    * AWSが提供する機械学習の知識がなくても、個々のユーザー向けにリコメンデーションをリアルタイムで提供できるサービスです。
* GCP Recommendations AI
    * https://cloud.google.com/recommendations?hl=ja
    * Recommendations AIは、Google Cloud Platformが提供するレコメンドエンジンであり、Googleの機械学習アルゴリズムを利用しています。
* アルゴリズム
    * 協調フィルタリングやコンテンツベースフィルタリングは、一般的にアルゴリズムが公開されているので、RubyやPythonで独自に実装することも可能です。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
機能自体シンプルであるため、メインの機能は利用しやすいかなと思います。
デザインがbootstrapでシンプルすぎるかなといったところがあるので、bootstrapの無料テンプレートサイトなどを参考にしながら、メニューやボタンなどこのアプリの世界観に合うUIにするといいかなと思います。
また全体的なUIのまとめとして[ソシオメディア - デザインパターン](https://www.sociomedia.co.jp/category/uidesignpatterns)などを参考にするといいかなと思います。
その他、現状で気になる点を下記にあげているのでご確認ください。

- 曲作成をする導線はヘッダーよりは一つのページの中に準備しておきましょう。ヘッダー内の場合は他のページに遷移しても表示される部分なので、機能を適用するページへの導線をヘッダーに載せるのが主な使い方になります。（ログイン画面やユーザー登録画面でも曲作成が表示されるのは他の機能に目が取られるので違和感ですね）
- 曲を自動作成した際に再度作成する場合の導線を作っておきましょう。自動作成した曲がいいかどうかをユーザーに委ねるとした場合は、再生や停止ボタンと同じ並列で再度作成する導線を設けるのがいいかなと思います。
- 登録練習曲一覧については検索できるようにしましょう。

## 最後に
上記内容を確認いただきタスクをissueで書き出したら、こちらのissueはcloseしていただいて大丈夫です。

また上記の内容を踏まえて本リリースまでのスケジュール感を教えていただければでございます。

**Comment by kawamura-chuko** [comment]
@kerochelo 
レビューの実施ありがとうございました。
各タスクについて、issueで書き出しましたので、このissueはclose致します。
本リリースは9月頭あたりを目指して進めていきたいと考えております。
